### ISSUE TITLE
Each PowerFlow must have its own GridPowerCorrected and LoadPowerCorrected

### ISSUE THREAD

**Issue by christoh** [christoh/FroniusMonitor#30]
We can use global correction factors as there is only one primary meter per site. However, each Gen24PowerFlow needs its own GridPowerCorrected and LoadPowerCorrected. In case of any additional Inverter which is not connected to a primary meter the correction factor should not be used (i.e. always use 1.0)

![Image](https://github.com/christoh/FroniusMonitor/assets/17645550/202ee798-eff0-496b-94bf-6da1f5a3e6ce)

![Image](https://github.com/christoh/FroniusMonitor/assets/17645550/9354e8e5-cee5-48ba-a86c-63cb7f3f9a62)

![Image](https://github.com/christoh/FroniusMonitor/assets/17645550/b0da5430-139d-4529-9a37-46244efc2eea)

**Comment by HugoX104447** [comment]
So it shall look like this (taking your pictures above as example)?

Homeautomation contains:

- Firtzbox
     -  SmartDevices
- Toshiba HAVC
- SolarSystem
    - One network operator grid meter
         - Drifts associated with the operator grid meter
    - One primary fronius inverter
         - One primary fronius smart meter (associated with the primary inverter and grid meter)
     - Some more fronius inverter
         - Some more fronius smart meter
- WattPilot

What else can the corrected values be used for? So in an essence, the Powerflow shouldn't be modified at all, the UI or one of the models (not sure which one, still catching up) should just do the calculation and update the values for the operator grid meter?

**Comment by HugoX104447** [comment]
Btw, I started splitting up the home automation system. The idea is like as outlined above, to have the home automation system a solar system associated, consisting of the several independent solar components (like your inverters) reporting their solar power etc, and the solar system also having the sole control over the drifts and exposing the corrected values for the grid meter (based on the primary smart meter). Please let me know if that makes sense to you, or if i step on your toes and you started to work on that already? I did not create a pull request, but here's a [Link](https://github.com/christoh/FroniusMonitor/compare/master...HugoX104447:FroniusMonitor:refactor-homeautomation)

**Comment by christoh** [comment]
It makes sense but it is indeed too time-consuming for me to monitor this. I cherry-picked two commits and will do refactorings for HomeAutomationSystem, Settings etc. when time permits. Currently this has no urgency.
